---
title: "Loosening the Thread that Hangs the Sword of Damocles"
#Alternative:
#title: "Careful what you wish for"
subtitle: "Do Legislators Change Their Behavior When It Becomes Easier to Recall Them?"
author: "William Zhu"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: pdf_document
header-includes:
    - \usepackage{setspace}
    # - \linespread{2}
    - \doublespacing
    
    # - \usepackage{lineno}
    # - \linenumbers
csl: ../../template/american-journal-of-political-science.csl
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(dplyr)
# library(tidyr)
# library(stargazer)
# library(did)
```

## Introduction

Incumbents seek re-election. To be reelected, it is usually beneficial, if not necessary, for them to seek their parties' nomination. As a result, they often, if not always, do the parties' bidding. Understandably, the public is none too pleased with the stranglehold of the parties on politics, which are deemed to be responsible for all sorts of ills of the body politic: corruption, polarization, unaccountability, etc.

Consequently, popular demand for and subsequent implementation of electoral institutions aimed at curbing the power of parties have been always been around since the birth of mass democracy which gave birth to the very idea of modern political parties. Among those institutions, recalls are unique in that they can directly shorten an elected official's term before the next election arrives and are thus most likely to force the official to rebel against their party leaders from time to time.

However, aside from the trailblazing work of @gordon2021 on recall elections' effect on elected judges in California, systematic assessment of recall elections' effect on incumbents is essentially non-exsistent. In addition to the methodological challenges mentioned by @gordon2021, perhaps another important reason lies in the lack of credible threat due to prevalent institutional obstacles of recalling an elected official. In the case of judicial recalls in California, the high number of signatures required to trigger one,[^1] combined with its rarity[^2] and the resultant norm against recalling judges, have historically made the threat of recall very much negligible. It is no wonder that Californian judges only just began to take the threat of recall seriously, even though this mechanism has been on the statute book for decades. In addition, due to the nonpartisan nature of judicial elections and recalls in California, @gordon2021 did not address the role of party of recall elections.

[^1]: In the case of Persky's recall, 58,634 valid signatures must be collected within 160 days to put Persky's name on the recall ballot. Source: Ballotpedia, [https://ballotpedia.org/Aaron_Persky_recall,\_Santa_Clara_County,\_California\_(2018)](https://ballotpedia.org/Aaron_Persky_recall,_Santa_Clara_County,_California_(2018)).

[^2]: See @spivak2020 [ p.85]'s account of the few past occurrences of past judicial recalls in US.

Fortunately, on the other side of the Pacific Ocean, Taiwan has just begun experimenting with recall elections on a national scale.

## Background

### Changing electoral system for legislative elections

Do legislators change their behavior it becomes easier to recall them?

### Changing rules for calling a recall election

### What goes around comes around

## Related Research

### Policy Preference

### Position Taking

## Data and Approach

### Causal Identification



### Measurement of Legislative Behavior

1.  Roll Call (Deviation from Party Leadership)
2.  Bill Co-sponsorship
3.  Three-Minute Speeches
4.  Ministers' Question Time

\newpage

## Bibliography

::: {#refs}
:::

<!-- \newpage -->

<!-- # Appendix -->

<!-- ## Data Collection -->

<!-- To begin with, we consider elections held between 2020 and now in countries which, at the time of the election, were graded as "liberal democracies" or "electoral democracies" by V-Dem. -->

<!-- ```{r vdemdata, echo=FALSE, results='asis'} -->

<!-- library(vdemdata) -->

<!-- vdem_2020_now <- filter(vdem, year > 2019) -->

<!-- identifier_list <- c("country_name", "country_id", "country_text_id") -->

<!-- vdem_high_level_indices_list <- c("v2x_polyarchy", "v2x_libdem", "v2x_partipdem", "v2x_delibdem", "v2x_egaldem") -->

<!-- vdem_regime_of_the_world <- c("v2x_regime", "v2x_regime_amb") -->

<!-- pt_est_dems <- filter(vdem_2020_now, v2x_regime > 1) -->

<!-- pt_est_dems_names <- distinct(select(pt_est_dems, country_name)) -->

<!-- vdem_2020_now_essential <- select(pt_est_dems, one_of(c("year",identifier_list, vdem_high_level_indices_list, vdem_regime_of_the_world)  ) ) -->

<!-- # ci_est_dems <- filter(vdem_2020_now, v2x_regime_amb > 3) -->

<!-- # ci_est_dems_names <- distinct(select(ci_est_dems, country_name)) -->

<!-- knitr::kable(pt_est_dems_names) -->

<!-- ``` -->
