---
title: "Literature Review and Theory"
# subtitle: "Demand for Personal Vote"
author: "William Zhu"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: pdf_document
fontsize: 11pt
geometry: "left=1.5in,right=1in,top=1in,bottom=1in"
header-includes:
    - \usepackage{setspace}
    # - \linespread{2}
    - \doublespacing
    
    # - \usepackage{lineno}
    # - \linenumbers
# csl: ../../template/american-journal-of-political-science.csl
bibliography: theory_references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
# library(stargazer)
# library(did)
```

<!-- Word count: `r as.integer(sub("(\\d+).+$", "\\1", system(sprintf("wc -w %s", knitr::current_input()), intern = TRUE))) - 20` -->

# Recall's Effect on Incumbents

## Examining Recalls of Individuals

Institutional arrangements for recalls vary wildly from one jurisdiction to another. In addition to the recall of individual elected officials, the entire legislative or executive branch may be recalled by triggering a new general election [@welp2020]. Ideally, it would be great to develop a theory that applies to all mechanisms of recall in existence. However, such a theory may be called on to explain qualitatively different behavioral patterns and thus either become too vague to make a significant contribution to the extant literature or too complex for this exploratory work. Furthermore, the data required to satisfactorily identify the causal mechanism underlying such a theory would be immense and hard to come by. To facilitate discussion, recall elections will hereinafter only refer to those that meet the following criteria, which, to my knowledge, not only apply to all the recall devices operational in Taiwan, which serve as the test case, but also those in English-speaking jurisdictions around the world:

1.  Only individual politicians can be recalled.
2.  A recall election can only be triggered when enough eligible voters sign a petition for it.

Restriction of the scope of recalls under examination also hint at the perspective of this article which seeks to understand the behavioral pattern from the standpoint of individual politicians instead of collectivities like parties.

## Sketch of Theory

Following the tradition of *The American Voter*, I begin by identifying three categories of factors that affect a voter's decision in an election: partisan identification, policy orientation, and candidate evaluation [@campbell1960, p. 59; @lewis-beck2008, p. 28]. Though voters' decisions have long been dominated by voters' partisan identification, policy orientation and evaluation remain important components of their decision calculus such that electoral swings hinge on them.[^1] Therefore, the confluence of these different kinds of factors means that the message of each election is frequently far from clear, notwithstanding widespread claims in mass media otherwise. From the vantage point of this classical theory of voting behavior, it does not take many extra steps to view institutions of direct democracy as means to allow the electorate to send a clearer message by filtering only the pertinent factor from the rest when they are called to the polling stations. Referenda and initiatives allow voters to express and enact their policy preferences directly by a simple yes or no an each proposition, potentially overcoming partisan divides and incumbents' stranglehold on popular measures. <!-- start recall --> Similarly, recalls afford voters with a clean-cut fashion of evaluating their elected officials. When the recall election is held, one archetypal question is put to the voters: do you want to remove the incumbent officeholder from the office immediately? In this question, there is neither partisan cue nor policy questions, thus isolating voters from the influence of party identification and policy evaluation as much as possible. If the recall attempt fails, the incumbent gets to stay in the office. It is only when the recall is successful that voters might be given a chance to decide how to fill the vacancy. These institutional arrangements common to most if not all recalls mean that voters may to still vote for their own party's candidate should the recall succeeds, further removing a significant chunk of partisan identification from their decision calculus at the recall election.[^2]

[^1]: For a more thorough review of the voting behavior literature, see @bartels2010 and @jacoby2010.

[^2]: @thepoli2020 provide a more historical and critical approach to understanding the rationale and practice of recall.

Nevertheless, theoretical potential afforded by the institution of direct democracy to express their preference for policies and incumbents may not materialize fully. Parties and popular elected officials have successfully mobilized the electorate to vote along party lines in referenda and initiatives[@branton2003; @bowler2010]. Recall elections certainly are not immune to partisan coordination either [@masket2016]. Nevertheless, the potential is always there, and arguably voters have repeatedly recalled elected officials that would have been reelected had the forces of partisan identification been given a chance to prevail on the usual election day [@gerston2004]. Furthermore, relying on the forces of partisan identification to tide through a recall attempt is a particularly risky choice for elected officials fighting for their job in marginal constituencies where even a mild swing against them may give them the boot. It thus stands to reason that even when partisan coordination is taken into account or even assumed to be perfect, demographic shift, among other swing factors would reduce their job security, thus contributing the credible threat of recall, which, as the foregoing discussion suggests, causes voters to weigh their evaluation of the incumbent than they they would in a regular election. To put it succinctly, recalls should make politicians realize that the security of their positions hinge more on their personal labels than before.

## Definition of Personal Vote

As a result of the threat of recall, incumbents, <!-- Mayhew's assumption: single-minded seeker of reelections --> who are assumed to seek reelections single-mindedly [@mayhew1974], demand more electoral independence from their parties [@cain1987], which, especially given the greater importance of candidate evaluation to which voters attach, is best achieved by cultivating personal votes for themselves. To paraphrase what @mayhew1974 [p. 45] said about primary election, recall is just another election to be survived from the standpoint of the politicians.<!-- Definition --> @cain1987 [p. 9] define the personal vote as the "portion of a candidate's electoral support which originates in his or her personal qualities, qualifications, activities, and record." The significance of the personal vote has long been recognized, though the employment of this term is not so universal as it manifests itself throughf a different name or an analogous concept [electoral connection @mayhew1974; home style, @fenno1978; personal reputation @carey1995; dyadic representation, @miller1963; @weissberg1978; @ansolabehere2011; personal representation, @colomer2011; local vote, @pattie1995]. To clarify their defintion of the personal vote, @cain1987 [p. 9] further emphasizes the personal vote does not include

> "support for the candidate based on his or her partisan affiliation, fixed voter charactersistics such as class, religion, and ethnicity, reactions to national conditions such as the state of the economy and performance evaluations centered on the head of the governing party"

which will serve as my working defintion of "party vote." Even though this appears to exceed the scope portion of the support driven by the concept of partisan identification as defined by @campbell1960 [p. 121], it does mirror the national partisan electoral swing which, per @mayhew1974 [p. 28, 32], individual legislators, especially those representing marginal constituencies, cannot be reasonably be expected to control and should treat as acts of God. It should become apparent the key distinction here between the personal vote and the party vote is the degree to which an individual legislator may influence. It follows that the definition ties in with the portions of the policies and economic condition which individual legislators and parties for which may credibly seek credit, and only parties may credibly claim to be the state of economy and the success of policies that impact the entire electorate [@mayhew1974]. Therefore, the definitions of the personal vote and the party vote clearly correspond to the issues for which voters hold them responsible. Similarly, the party vote is also manifested through a different name or analogous concept [partisan representation @hurley1991; collective representation @weissberg1978; normal vote @converse1966; partisan reputation @carey1995] <!-- Note to self: converse's concept of normal vote needs better citation --> under many circumstances.

## Relationship between Personal and Party Votes

<!-- alterantive definition discussion -->

Before I further detail my theoretical prediction of recall's effect on an incumbent's demand for personal vote, it behooves me to clarify the relationship between the personal vote and the party vote which, as @carsey2017 put it, may lead to divergent theoretical prediction when this relationship is understood differently and thus should only be determined empirically. <!-- position taking issues --> @carsey2017 [p. 467-468] first divide personal vote into two components: one is ideological and the other non-ideological. Then they argue that since voters identified with the politician's party and those not identified with that party evaluate these two components differently and it is impossible to know how they do it except through assessment of empirical evidence, it follows that it is also impossible to know whether devoting more effort to pursuing personal vote may cost them the party vote, that is, whether there is a real tradeoff between party vote and personal vote.

While I do not contest that how this tradeoff works depend on empirical assessment of voters' response to legislative behavior, I do contend that the tradeoff must exist at some point. Indeed @carsey2017 [p. 467] admit that as long as ideology remains a substantial part of the contributing factors to personal vote, choosing a more liberal position always carries the risk of losing the support of more conservative voters regardless of the voter's party identification.<!-- To demonstrate this view, I propose to apply the technique of *reductio ad absurdium* --> <!-- first attempt to argue that the personal vote may be stripped of its position-taking component and considered as nothing but voters' response to elected officials' non-ideological activities, which, in the case of legislators, include constituency service and pork barrel. Although it is useful to consider the contribution of this aspect of politicians' activities to their electoral support, it is --> <!-- In some conceptualization where the party vote is always a constant, the candidate's job becomes even simpler as only one task remains: maximizing the personal vote under resource constraints. Such definitions and their associated predictions appear to conflict with common sense and political folklore, which, as @cain1987 [p. 123] have warned us, is a cause for pause.  --> <!-- Should there be no tradeoff between a politician's attempt to cultivate a party vote and a personal vote, then  --> <!-- the most progressive Democratic candidate could win more Republican votes than a Democrat in name only who is as conservative as any Republican simply because the former is better at delivering constituency service and pork. --> <!-- resource spent on personal vote is not spent on party affairs --> Even if the personal vote can be conceptualized in a non-ideological/non-policy fashion and focuses only the vote gained by delivering constituency services, pork barrels, and other non-ideologically-motivated activities, it is still improbable that devoting the maximal effort toward cultivating personal vote does not conflict with their pursuit of party vote. One penny and one second spent on heeding the needs of the constituents is one penny and one second not spent on party-building activities, say party strategy sessions, fundraising for the party's common war chest, and campaign activities endorsing copartisan candidates. Common sense and political folklore would predict that evading all calls on their time and purse to be a good team player in the party in order to grow a personal following does not bode well for their reputation among the party leadership and local activists, which would undermine their chances of renomination and, if successfully renominated, reelection. <!-- Tradeoff between two kinds of activities --> Therefore, I hold the conventional view that at a certain point, a candidate must face the tradeoff between the personal vote and the party vote which is not only grounded in classical microeconomic theory but also empirically supported [@ansolabehere2000; @primo2010]. <!-- . A candidate's time and resources are limited and devoting effort toward cultivating a personal vote, though not necessarily detracting the candidate's party vote, necessarily crowds out time and resources that could have been spent on cultivating a party vote, leading to a trade-off between activities geared toward cultivating the personal vote and those intended for building the party vote. <!-- hypothesis --> This discussion also provides a nice segue to my central hypothesis regarding the behavioral consequence of the threat of recall: **the time and resources a legislator expends toward cultivating personal vote,** ***cetris paribus***<!-- comma issue -->**,** **increases in the legislator's vulnerability to recall attempts.**

# Cultivating a personal vote against recall threats as a legislator

<!-- In the foregoing analysis, I have invoked the conventional assumption the legislators are single-minded seekers of reelection [@mayhew1974]. Although an oversimplification of the goals of legislators, this assumption has been deemed not only plausible in the American context but also across a wide varieties of democratic assemblies. To facilitate analysis, I shall continue to follow this assumption until there is sufficient ground to challenge it since reelection is not only an important goal for legislators but also instrumental in, if not essential to their attainment of other goals in the legislative arena and beyond, such as policy demands and positions of power. -->

As I have mentioned before, the recall is effectively yet another election incumbents need to survive to stay in the office, which is conventionally assumed to be the legislator's only goal. Toward that end, cultivating a personal vote can be an important strategy for all legsialtors. Of course, the extent to which this strategy is useful varies greatly depending on the broader institution in which legislators contend for survival. The pursuit of personal vote has long been documented and analyzed in the US where candidates belong to a party simply because they the candidates say so and the parties' ability to constrain their members' behavior is limited, providing more leeway for members of Congress to craft their own policies and positions [@mayhew1974; @cain1987; @cox2007] . The relative penury of the parties and the laxity of campaign finance regulations also allow individual candidates to build their own potent campaign machine independent of the party's support and devoted mostly to cultivating the candidates' personal bases of support. All told, the aforementioned factors that have helped the candidates to cultivate personal votes not only in the US but also in other democracies where weak parties or loose campaign finance regulations also persist [@carey2008; @reed1994; @crisp2021].

Moving beyond the aforementioned direct indicators of party strengths, institutionalists have identified constitutional distribution of power and electoral systems [@carey1995; @finocchiaro2018] as a more fundamental cause of the greater utility of activities in aid of seeking personal vote. Again, the starting point of this line of query can be traced to the US Congress where those activities is extremely prevalent. <!-- constitutional distribution of power --> The US Constitution provides for a presidential system of separation of power where members of Congress cannot serve in the executive branch; whereas in a parliamentary system, a prime minister must also be a member of parliament (MP), whose government, consisting also of MPs, retains the confidence of a majority of the MPs. Perhaps because the rewards at the disposal of party leadership in Congress appear less attractive than those offered by their counterparts in other parliaments, congresspeople may feel that they have less to gain from voting with their copartisans than parliamentarians in general [@cain1987]. Furthermore, the candidate-centered electoral system used for returning congresspeople encourages them to pursue more personal votes which are more valuable for legislators competing in party-centered electoral systems. These findings have similarly been corroborated across a varieties of institutional settings [@carey1995]. <!-- universal occurrence of pursuit of personal vote  --> That is not to say, however, that legislators contesting under party-based electoral systems do nothing to enhance their electoral independence from the party. Even in some of the most party-based electoral systems, efforts have been devoted to shield candidates from the uncertain electoral fate of the party by developing their personal brands, sometimes at the behest of party leadership [@shugart2005], suggesting that activities geared toward cultivating a personal vote is quite universal, even though the intensity of such pursuit varies.

To specify how legislators are incentivized by the threat of recall to devote more time and resources toward cultivating personal votes, I would like to point to another observation about recall devices to facilitate analysis. To date, no mechanisms provides for recalls of individuals elected on the basis of a party list. <!-- a collectivity, e.g. a party. Voters are only allowed to recall individual elected officials in Taiwan as is the case for all other jurisdictions where recalls are allowed.  --> Even though such a mechanism is technically conceivable that parties of individual legislators elected on the basis of party list, e.g., closed-list proportional representation (CLPR), open-list proportional representation (OLPR), can be recalled by the electorate, such practice, to my knowledge, has never existed, possibly because it defeats the point of instituting a party list electoral system where parties are the vehicles of representation as the name of the category suggests and thus given the final say as to which members of their parliamentary parties get to keep their job. This means that, realistically, only legislators chosen on the basis of candidate-centered electoral systems, e.g. first-past-the-post (FPTP), single transferable vote (STV), single nontransferable vote (SNTV), alternative vote (AV), can ever be recalled since voters technically return individuals instead of parties to the elected office, and are thus given the opportunity to recall them. Therefore, I believe that it is safe to assume that only legislators chosen on the basis on candidate-centered electoral systems can ever be recalled. <!-- Of course it is certainly possible that, due to my omission or some future institutional innovation, a legislator elected on the basis of the party list may be subject to recall attempts as well. --> <!-- As the foregoing discussion suggests, a party or legislators elected from the party list devote significant efforts to court personal votes and would not be immune to pressure to redouble their efforts should they be subject to recalls. One simply need to reconsider to whom those activities should be attributed as both party leadership and individual candidates on the party list might be responsible. -->

On the assumption that legislators facing the threat of recall contest in candidate-centered electoral systems, I now proceed to sketch the conditions incentivizing legislators to devote more efforts to cultivate a personal vote in response to the latent threat of recall. @cain1987 suggest that seniority and electoral uncertainty are key predictors of personal vote. Considering the personal vote as a stockpile of legislators accumulate over time and expend to counter electoral uncertainty, @cain1987 argue that legislators' demand for personal vote demand for personal vote decline in both seniority and electoral uncertainty. Later studies have 
<!-- not only  -->
corroborated this key finding [@hibbing1991; @ansolabehere2000].
<!-- but also specified elements contributing to electoral uncertainty, e.g. party dealignment [], constituency complexity [@ensley2009], coattail effects [], as well as how they gain personal votes through various positions of power, e.g. (sub)committee appointment, government portfolio, thereby decreasing their demand for more personal votes and thus their activities to that end.  -->
As recall constitutes an electoral uncertainty, it follows that similar pattern should be observed among legislators who can be recalled.

As for the activities pursued for the purpose of cultivating personal votes, legislators have a number of options which can be categorized into position taking, <!-- (which is usually ideological) --> and particularistic benefit provision. <!-- (which is usually nonideologlical) --> Members of the US Congress have a long history of enegaging in both kinds of activities to cultivate personal votes. However, taking an ideological position different from that of the rest of the party is a luxury for legislators who are more incentivized to toe the party line [@kam2014]. @mayhew1974 argues that a legislator's demand for personal vote should also decline in the amount of campaign resources controlled by the parties. Empirical evidence from US Congress and other legislative assemblies, especially those operating under parliamentary systems bears out this theory [@rohde1991; @cox2007; @carey2008; @depauw2009]. Nonetheless, party strength should not offset legislators' demand for personal vote as a result of the latent threat of recall. Keep in mind that even perfect partisan coordination and mobilization of voters is not foolproof against electoral swing against the incumbents, especially for the less experienced ones or those in marginal constituencies. Hence, one should still expect to observe a net increase in the amount of activities pursued for the purpose of cultivating personal votes. Under this condition, copartisans, desiring the same, if not lower, level of electoral uncertainty for themselves, must be willing to reduce some aspects of their intraparty cohesion. Drawing inspiration from dn and Vanberg's [-@martin2020] arguments on bargaining among the coalition partners, I also contend that the activities legislator undertake to pursue personal votes as a range of goods which are not equally "visible" among the whole electorate and thus make for good side payments that parties use to maintain their solidarity platform-wise[@cox2005; @jenkins2012]. Some goods, such as records of roll call vote and Minister's Question Time are highly visible and potentially damaging to a party's national reputation and thus the party vote across the board; other goods, such as constituency service and pork barrels outside the legislator's constituency and thus far less of an immediate concern for the party as a whole. Naturally, individual legislators may as well desire both the highly visible and the poorly visible goods, depending on their capacity for collective action. Since the party as a whole benefit from not demanding so many highly invisible goods for each individual legislator, the demand for highly visible goods would decline in the party's capacity for engaging in collective action. Following these arguments, I hypothesize that ***credible threat of recall increases legislators' demand for personal votes. And when parties are endowed more with more resources, personal votes will be more likely to pursued in a fashion that is less visible among the national electorate.***

\newpage

# Bibliography

::: {#refs}
:::
