---
title: "Literature Review and Theory"
subtitle: "Competing Principals in the Legislative Arena"
author: "William Zhu"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: pdf_document
header-includes:
    - \usepackage{setspace}
    # - \linespread{2}
    - \doublespacing
    
    # - \usepackage{lineno}
    # - \linenumbers
csl: ../../template/american-journal-of-political-science.csl
bibliography: theory_references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
# library(stargazer)
# library(did)
```

# Introduction

How can voters make sure that elected officials are on their best behavior? We can monitor them, and credibly threaten to vote them out when we don't like them anymore. However, the threat isn't always credible. When the election day comes, forces of partisan identification, incumbent effect, among numerous factors, may save their skin after all. Perhaps more importantly, voters may want to punish the officials sooner than the next election. To what other remedies can they resort?

The answer given by the Los Angeles voters is recall elections. To check the corruption in local government, a ballot measure was passed in the City of Angels to allow voters to hold recall municipal officials when the number of eligible voters who demand the recall passes a certain threshold. The same device was later on introduced to the entire California and spread to other states. However, systematic analysis of recall elections are rare because recall elections themselves are even rarer. Most of the extant literature on recall elections focused on just one recall elections: the 2003 California gubernatorial recall. Furthrmore, aside from the trailblazing work of @gordon2021 on recall elections' effect on elected judges in California, systematic assessment of the effect of recall elections on incumbents' behavior is essentially non-existent. Aside from the methodological challenges mentioned by @gordon2021, perhaps another important reason lies in the lack of credible threat due to prevalent institutional obstacles of recalling an elected official. In the case of judicial recalls in California, the high number of signatures required to trigger one, combined with its rarity and the resultant norm against recalling judges, have historically made the threat of recall very much negligible. It is small wonder that Californian judges only just began to take the threat of recall seriously, even though this mechanism has been on the statute book for nearly a century.

In addition, unlike judges who are supposed to be fair and unswayed by public opnions as much as possible, most elected officials are supposed to represent and internalize the opinions of a number of political actors. Therefore, while it is reasonable to expect judicial recalls to cause judges to consider the opinions of their constituents who are in all likelihood the only group of political actors that matter to their decision process, it is far from certain whether other elected officials would consider constituents' opinions when they are under the pressure of a number of political actors, say parties, pressure groups, other than their constituents that push them in different directions.

<!-- Furthermore, unlike judges [@gordon2021, p. 7], most elected officials go out of their way to supply voters with verifiable information on which voters may evaluate their performance. -->

Fortunately, for students of direct democracy, a new experiment is under way on the other side of the Pacific Ocean, presenting us a better opportunity to probe the effect of recall elections where incumbents face pressure from a number of different directions. In 2016, Taiwan passed new legislation that made it much easier for voters to trigger recall elections of the vast majority of elected officials on every level of government. Recall elections has become a recurring event since then, and the threat to recall elected officials in Taiwan appears more credible.

I propose to evaluate the extent to which incumbent legislators behave differently as a result of the new recall rules by using difference-in-difference (DiD) approach which leverages Taiwan's mixed-member electoral system. In Taiwan, each voter gets two votes at a legislative election: one vote goes toward electing the legislator in a single-member district (SMD) under the system of first-past-the-post (FPTP), and the other one goes toward selecting a party list in a single national multi-member district (MMD) under the system of closed-list proportional representation (CLPR). Since dual candidacy in both contests is not permitted, legislators face a distinct set electoral incentives unlike other mixed-member electoral system where legislators fail to win the hearts and minds of local constituents could still be returned to the legislature by the strength of their parties and their positions on the party lists in a larger constituency. Furthermore, perhaps due to the institutional setup where parties rather than the local constituents that choose the legislators in the PR tier, they can only be removed by the party itself and could never be recalled by the voters before and after the passage of the new recall election. This allows us to treat the legislators in the PR tier as the control group and those in the FPTP tier the treatment group. I propose to choose measure four kinds of legislative behavior: roll call votes, bill co-sponsorship, three-minute speeches, and ministers' question time to detect whether legislators change their behavior because it is easier to recall them.

# Theory of Legislative Behavior

## Behavioral Foundations

Partisan identification are strong predictors of voting behavior in almost all democracies. A large part of what makes partisan identification powerful consists in parties' stable policy position, and their promise to implement their policies. Therefore, copartisan legislators have a strong incentive to support the same policy. Institutions may reinforce copartisan legislators' unity in the legislative party. Its effect is most pronounced in CLPR electoral system where only one national MMD exists. Supporting the party line helps them to not only get a higher position on the party list which is decided by the party leadership but also present a clear alternative to voters as to which policy each party supports.

Meanwhile, legislators also face a strong incentive not to support their copartisans' policies from time to time. Voters may evaluate legislators in a better light if they don't always stick to the party line and stake out their own position to represent their constituents. Electoral systems like single-member district FPTP and single nontransferable vote (SNTV) also encourage this type of behavior.

As a result, legislators are pulled by at least two kinds of forces in. One force comes from the party which is concerned with the electoral fate of the party as a whole and thus may reflect the preferences of those who voted for them across the country. Another force comes from the constituents who may affect the electoral fate of individual legislators and usually more concerned with local issues. Legislators may breathe a sigh of relief if their constituents and parties pull them in the same direction. This is especially true for legislators elected from a party list as their electoral fate depends entirely on the party's performance as a whole and the benefits of sticking with their copartisans far outweigh the cost thereof. For those legislators running in SMDs, especially those elected in swing districts, they must take pain to avoid angering at least one of them. Therefore, throughout this article, I will focus on discussing the behavior of legislators running in SMDs. It further justifies this paper's identification strategy which I have briefly previewed and will explain in greater details.

## Framework

Given that legislators running in SMDs are pulled in different directions by different kinds of forces, it is useful to consider this problem from a principal-agent perspective which has been frequently employed to consider how an array of political actors may influence their behavior like state governors, presidents. However, since Taiwan is a unitary country where a robust two-party system in place, local officials are endowed with limited resources to influence the behaviors of the member of Taiwan's Legislative Yuan (LY), whereas the interest of the president and her legislative party are by and large aligned as both of them are concerned with their party's electoral fate across the whole country. This gives us theoretical reason to be parsimonious with our model by assuming that individuals legislators as agents answer to at most two agents: parties and local constituencies.

While the debate as to whether the members of the legislative party share similar interests and preferences is difficult to resolve due to a number of theoretical and empirical difficulty, it is a relatively uncontroversial observation that parties possess a great deal of means and resources to monitor their copartisans' behavior and to pressure them to act accordingly. On the other hand, individual constituents don't usually share the same interests and preferences with their representatives. Even aggregate opinion of the constituency doesn't always line up with that of the legislator and that of the party. In addition, constituents lack the means and resources to effectively monitor and ensure that legislators act the way they want. Therefore, the incongruence of interests and preferences between the legislative party and the constituencies that elect at least some of its members and the disparity of resource endowment and means availability guarantees that at least one of them seek to induce better behavior on the part of individual legislators.

To further specify the theoretical structure, I intend to structure the problem such that both constituents and the legislative party are principals competing for the loyalty of individual legislators. Though it implies that parties impose discipline on their members in the legislature, there are a number of reasons for doing so. First, the adoption of this kind of theoretical structure has a long pedigree with a good amount of empirical support. Second, in all likelihood, having two competing principals wouldn't yield a prediction different from that in a setting where constituent voters are the only principal, especially when the set of choices is is binary. Third, even if the set of choices is not binary, it is possible to collapse the problem to a simple principal-agent problem simply by setting the preferences and interests of copartisan legislators identical. Finally, given that the strength of legislative parties in Taiwan are very similar to those in other parliamentary systems where party discipline is usually assumed to be operative, it is a reasonable assumption.

Since different ways of measuring legislative behavior entails different sets of choices among which the legislator must pick. It is difficult to propose which exact kind of behavior should be expected. As a result, most specific hypotheses must be reserved for the section where I will discuss how each measurement relates to the theory. Here, one must be content with a general description of how aligned individual legislators with each principal. Carrey predicts that, *ceteris paribus* , institutions that give constituents more control over legislators will cause them not to toe the party line more frequently. A study of European Parliament suggests that when their electoral fate becomes more unpredictable, legislators' behavior are more aligned with principals who are better at helping them get reelected, and in the case of the study, their national party instead of the european party group leader. Some suggest that when both principals demand the legislators to take a stand on opposite sides of an issue or pursue a positive policy different from the status quo, legislators may avoid taking a stand at all and stick to the status quo as their negative policy. These predictions need not conflict with each other, especially with respect to the cases analyzed in each of these studies. However, in order for the predictions to travel farther, it should make predictions for various kinds of principals competing for the loyalty of individual legislators.

## Theory of the Effect of Recalls: A Sketch

### Who would potentially vote in recall elections?

#### Like a mid-term election

In both recalls and elections, the set of outcome for incumbents is basically the same: voted out of office or remain in office. In addition, rules on recalls usually specify that an elected official who has survived the recall election cannot be recalled within a pre-determined amout of time. Furthermore, recalls are unlikely to happen around the beginning of the incumbent's term. Therefore, the existence of recall means that for each legislators there is always a mid-term election (in the sense that it takes place during the middle of the term of the incumbent officeholders, instead of the term of the president which is how it is usually understood). A number of observation about mid-term elections could be directly applied, including the lower turnout rate and how the composition of voters in mid-term elections differs from the legislative elections coincide with presidential elections [Note: In Taiwan, legislative elections now always coincide with presidential elections due to the electoral reform passed in 2005.]

#### Like a general election

The threat of recall elections may usually result from an intense negative attitude toward the incumbent. Even when only just 10% of eligible voters signed the petition, it is still a substantial slice of voters whose animus toward the incumbents was strong enough to motivate them to sign a petition, serving as a bellwether for worse to come. Accounts of past recalls in the US suggests that recalls are emotionally charged events where turnout rate match and even surpass that at presidential elections.

#### Overwhelmingly hostile voters

Negative voting has also been well documented phenomenon where assessment of candidate performance is generally negative, leading voters not to vote for the incumbent. It can also be helped by the fact that not only are partisan cues removed, reducing the effectiveness of partisan identification. Partisans can justify to themselves that voting to recall them does not necessarily come at the expense of handing the helm of government to a different party. Successful recalls in Taiwan entail special elections where voters identifying with the incumbents' parties still get to pick their copartisans to fill the office.

#### Empirical Evidence from Taiwan

Prediction the composition of voters the next general election can be relatively accurate since it takes place with a certain degree of regularity. Estimation of the composition of voters in case of recalls is hard. Lack of data and the usually *sui generis* nature of each issue that tiggers a recall.

#### Assumption

Legislators act on the assumption that voter composition is like that in general election. Incumbents attracting overwhelmingly hostile voters are in all likelihood toast and unrepresentative. Careerist incumbents are the norm. They make the assumption that general election voters are coming.

### What factors motivate recall voters' behavior?

Issue

Candidate evaluation

Partisan identification

### What may incumbents do to ward off threat of recall?

### What may parties do to ward off disunity?

### What are the possible outcomes?

#### Party values core voters

Preserving party unity reinforces partisan identification which matters most to turning out core voters. Parties are willing to ensure that publicly visible behavior of legislators must remain consistent with party platforms.

#### Party values swing voters

Cultivating personal votes in marginal seats helps the party to retain them when the electoral fate turns against them. Parties are willing to ensure that publicly visible behavior of legislators demonstrate that not those representing marginal constituencies need not toe the party line.

#### Threat of recall elections is not credible for most incumbents

Nothing happens. Threat of recall elections is not credible, and incumbents just go on like usual.

## Identification Strategy: Mixed-Member Electoral System

### Literature Review of Mandate Divide Hypothesis

### Literature Review of Difference-in-Difference Strategy

### Identifying Assumptions

## Measurement

## Analysis

\newpage

## Bibliography

::: {#refs}
:::
