---
title: "A New Typology of Electoral Systems"
author: "William Zhu"
date: "5/5/2022"
header-includes:
    - \usepackage{setspace}\doublespacing
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

<!-- Studies of electoral systems usually focus on the independent effect of one  -->
<!-- parameter of an electoral system [Citation needed]. Such tendency is  -->
<!-- understandable since it narrows our focus. However, the merits of this approach  -->
<!-- may be outweighed by its deficiencies. Frequently, contradictory results can be  -->
<!-- reached by tweaking the methodology.  -->

Institutionism assumes that change in institution may cause 
the political behavior to change. Most if not all students of electoral systems 
accept this assumption and undertake the task of uncovering the effect of tweaking
institutional parameters wherever possible. 
Usually, this is done by answering the simple question: *ceteris paribus*, does changing certain 
institutional feature makes people more likely to do something? 
This simple approach has advanced our 
understanding of electoral systems by leaps and bounds thanks to increasing 
availability of data and sophistication of technology. 

Nevertheless, too many important questions about electoral systems evades this 
easy approach. Duverger's Law