---
title: "Literature Review and Theory"
# subtitle: "Demand for Personal Vote"
author: "William Zhu"
# date: "`r format(Sys.Date(), '%d %B %Y')`"
output: pdf_document
fontsize: 11pt
indent: true
geometry: "left=1.5in,right=1in,top=1in,bottom=1in"
header-includes:
    - \usepackage{indentfirst}
    - \usepackage{setspace}
    # - \linespread{2}
    - \singlespacing
    # - \doublespacing
    # - \usepackage{lineno}
    # - \linenumbers
# csl: ../../template/american-journal-of-political-science.csl
bibliography: theory_references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
# library(stargazer)
# library(did)
```


# Cultivating a personal vote against recall threats as a legislator

<!-- In the foregoing analysis, I have invoked the conventional assumption the legislators are single-minded seekers of reelection [@mayhew1974]. Although an oversimplification of the goals of legislators, this assumption has been deemed not only plausible in the American context but also across a wide varieties of democratic assemblies. To facilitate analysis, I shall continue to follow this assumption until there is sufficient ground to challenge it since reelection is not only an important goal for legislators but also instrumental in, if not essential to their attainment of other goals in the legislative arena and beyond, such as policy demands and positions of power. -->

Recall is effectively yet another election incumbents need to survive to stay in the office, which is conventionally assumed to be the legislator's only goal in order to help formulate the model of legislative behavior. To ward off the threat of recall such that it never gets triggered in the first place, cultivating a personal vote is an important strategy for all legsilators. Of course, the extent to which this strategy is useful varies greatly depending on the broader institution in which legislators contend for survival. The pursuit of personal vote has long been documented and analyzed in the US where candidates belong to a party simply because they the candidates say so and the parties' ability to constrain their members' behavior is limited, providing more leeway for members of Congress to craft their own policies and positions [@mayhew1974; @cain1987; @cox2007] . The relative penury of the parties and the laxity of campaign finance regulations also allow individual candidates to build their own potent campaign machine independent of the party's support and devoted mostly to cultivating the candidates' personal bases of support. All told, the aforementioned factors that have helped the candidates to cultivate personal votes not only in the US but also in other democracies where weak parties or loose campaign finance regulations also persist [@carey2008; @reed1994; @crisp2021].

Moving beyond the aforementioned direct indicators of party strengths, institutionalists have identified constitutional distribution of power and electoral systems [@carey1995; @finocchiaro2018] as a more fundamental cause of the greater utility of activities in aid of seeking personal vote. Again, the starting point of this line of query can be traced to the US Congress where those activities is extremely prevalent. <!-- constitutional distribution of power --> The US Constitution provides for a presidential system of separation of power where members of Congress cannot serve in the executive branch; whereas in a parliamentary system, a prime minister must also be a member of parliament (MP), whose government, consisting also of MPs, retains the confidence of a majority of the MPs. Perhaps because the rewards at the disposal of party leadership in Congress appear less attractive than those offered by their counterparts in other parliaments, congresspeople may feel that they have less to gain from voting with their copartisans than parliamentarians in general [@cain1987]. Furthermore, the candidate-centered electoral system used for returning congresspeople encourages them to pursue more personal votes which are more valuable for legislators competing in party-centered electoral systems. These findings have similarly been corroborated across a varieties of institutional settings [@carey1995]. <!-- universal occurrence of pursuit of personal vote  --> That is not to say, however, that legislators contesting under party-based electoral systems do nothing to enhance their electoral independence from the party. Even in some of the most party-based electoral systems, efforts have been devoted to shield candidates from the uncertain electoral fate of the party by developing their personal brands, sometimes at the behest of party leadership [@shugart2005], suggesting that activities geared toward cultivating a personal vote is quite universal, even though the intensity of such pursuit varies.

To specify how legislators are incentivized by the threat of recall to devote more time and resources toward cultivating personal votes, I would like to point to another observation about recall devices to facilitate analysis. To date, no mechanisms provides for recalls of individuals elected on the basis of a party list. <!-- a collectivity, e.g. a party. Voters are only allowed to recall individual elected officials in Taiwan as is the case for all other jurisdictions where recalls are allowed.  --> Even though such a mechanism is technically conceivable that parties of individual legislators elected on the basis of party list, e.g., closed-list proportional representation (CLPR), open-list proportional representation (OLPR), can be recalled by the electorate, such practice, to my knowledge, has never existed, possibly because it defeats the point of instituting a party list electoral system where parties are the vehicles of representation as the name of the category suggests and thus given the final say as to which members of their parliamentary parties get to keep their job. This means that, realistically, only legislators chosen on the basis of candidate-centered electoral systems, e.g. first-past-the-post (FPTP), single transferable vote (STV), single nontransferable vote (SNTV), alternative vote (AV), can ever be recalled since voters technically return individuals instead of parties to the elected office, and are thus given the opportunity to recall them. Therefore, I believe that it is safe to assume that only legislators chosen on the basis on candidate-centered electoral systems can ever be recalled. <!-- Of course it is certainly possible that, due to my omission or some future institutional innovation, a legislator elected on the basis of the party list may be subject to recall attempts as well. --> <!-- As the foregoing discussion suggests, a party or legislators elected from the party list devote significant efforts to court personal votes and would not be immune to pressure to redouble their efforts should they be subject to recalls. One simply need to reconsider to whom those activities should be attributed as both party leadership and individual candidates on the party list might be responsible. -->

On the assumption that legislators facing the threat of recall contest in candidate-centered electoral systems where legislators represent geographical constituencies, I now proceed to sketch the conditions incentivizing legislators to devote more efforts to cultivate a personal vote in response to the latent threat of recall. @cain1987 suggest that seniority and electoral uncertainty are key predictors of personal vote. Considering the personal vote as a stockpile of legislators accumulate over time and expend to counter electoral uncertainty, @cain1987 argue that legislators' demand for personal vote demand for personal vote decline in both seniority and electoral uncertainty. Later studies have 
<!-- not only  -->
corroborated this key finding [@hibbing1991; @ansolabehere2000].
<!-- but also specified elements contributing to electoral uncertainty, e.g. party dealignment [], constituency complexity [@ensley2009], coattail effects [], as well as how they gain personal votes through various positions of power, e.g. (sub)committee appointment, government portfolio, thereby decreasing their demand for more personal votes and thus their activities to that end.  -->
As recall constitutes an electoral uncertainty, I hypothesize that ***credible threat of recall increases legislators' activities aimed at cultivating personal votes.*** 

As for the activities pursued for the purpose of cultivating personal votes to counter this credible threat, legislators have a number of options which can be categorized into position taking, <!-- (which is usually ideological) --> and particularistic benefit provision. <!-- (which is usually nonideologlical) --> Members of the US Congress have a long history of enegaging in both kinds of activities to cultivate personal votes. However, taking an ideological position different from that of the rest of the party is a luxury for legislators who are more incentivized to toe the party line [@kam2014]. @mayhew1974 argues that a legislator's demand for personal vote should also decline in the amount of campaign resources controlled by the parties. Empirical evidence from US Congress and other legislative assemblies, especially those operating under parliamentary systems bears out this theory [@rohde1991; @cox2007; @carey2008; @depauw2009]. Nonetheless, party strength should not offset legislators' demand for personal vote as a result of the latent threat of recall. Keep in mind that even perfect partisan coordination and mobilization of voters is not foolproof against electoral swing against the incumbents, especially for the less experienced ones or those in marginal constituencies. Hence, one should still expect to observe a net increase in the amount of activities pursued for the purpose of cultivating personal votes. Under this condition, copartisans, desiring the same, if not lower, level of electoral uncertainty for themselves, must be willing to reduce some aspects of their intraparty cohesion. Drawing inspiration from Martin and Vanberg's [-@martin2020] arguments on bargaining among the coalition partners, I also contend that the activities legislator undertake to pursue personal votes as a range of goods which are not equally "visible" among the whole electorate and thus make for good side payments that parties use to maintain their solidarity platform-wise [@cox2005; @jenkins2012]. Some goods, such as records of roll call vote and Minister's Question Time are highly visible and potentially damaging to a party's national reputation and thus the party vote across the board; other goods, such as constituency service and pork barrels outside the legislator's constituency and thus far less of an immediate concern for the party as a whole. Naturally, individual legislators may as well desire both the highly visible and the poorly visible goods, depending on their capacity for collective action. Since the party as a whole benefit from not demanding so many highly invisible goods for each individual legislator, the demand for highly visible goods would decline in the party's capacity for engaging in collective action. Following these arguments, I further hypothesize that ***when parties are endowed more with more resources, legislators who want to protect themselves from potential recall attempts will be more likely to be pursue personal votes in a fashion that is less visible among the national electorate.***

\newpage

# Bibliography

::: {#refs}
:::
